landing_zone:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: ""
      port: 5432
      dbname: landing_zone
      schema: public
      threads: 1
      keepalives_idle: 0
      timeout: 300
